### ISSUE TITLE
Support for multi-database

### ISSUE THREAD

**Issue by davidlrosenblum** [dataiku/dss-plugin-neo4j#23]
Has there been any though for supporting the multi-database features in 4.x?  It seems, that the schema scan is only against the default database (neo4j).  And I don't see any what of providing that information in the dialog forms.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/21196824/119402513-0a1c7a00-bcab-11eb-81f8-682038224b21.png">

**Comment by jbelafa** [comment]
so Indeed we can add an option to define multiple sessions  that would target  different databases . 
We can probably add this to the parameter set  definition  however I am not certain  what huge difference it would make compared to a different URI  - which I suppose can have the database set as well. In the python client these are 2 separated sessions so I hardly see  any effective optimisation brought bit such an implementation. 
At least for configuration clarity  (for users whom would be given the specific database)  so it's still worth the implementation but  at a very low priority
 ( Alsor this is an Enterprise feature  so if you want to develop this , you need an "enterprise" neo4j instance )

**Comment by davidlrosenblum** [comment]
I was informed and tested that as of version 1.3.0 of the neo4j plugin that you can add the database to the end of the URL to accomplish what we want.
E.g. neo4j://hostname:boltport/databasename
