### ISSUE TITLE
Can't export data to Neo4j

### ISSUE THREAD

**Issue by SulimanLab** [dataiku/dss-plugin-neo4j#9]
The description of the plugin says and I quote "The Neo4j plugin allows DSS users to read and write from/to the Neo4j graph platform"

but I can't manged to push data to Neo4j

**Comment by StanislasGuinel** [comment]
Thank you for your feedback. The documentation will be changed as the "write" capabilities have not been published yet to the plugin store.

**Comment by SulimanLab** [comment]
> Thank you for your feedback. The documentation will be changed as the "write" capabilities have not been published yet to the plugin store.

is there any plans to add it in the future ?
